/* automatically generated by rust-bindgen */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub const PaHostApiTypeId_paInDevelopment: root::PaHostApiTypeId = 0;
    pub const PaHostApiTypeId_paDirectSound: root::PaHostApiTypeId = 1;
    pub const PaHostApiTypeId_paMME: root::PaHostApiTypeId = 2;
    pub const PaHostApiTypeId_paASIO: root::PaHostApiTypeId = 3;
    pub const PaHostApiTypeId_paSoundManager: root::PaHostApiTypeId = 4;
    pub const PaHostApiTypeId_paCoreAudio: root::PaHostApiTypeId = 5;
    pub const PaHostApiTypeId_paOSS: root::PaHostApiTypeId = 7;
    pub const PaHostApiTypeId_paALSA: root::PaHostApiTypeId = 8;
    pub const PaHostApiTypeId_paAL: root::PaHostApiTypeId = 9;
    pub const PaHostApiTypeId_paBeOS: root::PaHostApiTypeId = 10;
    pub const PaHostApiTypeId_paWDMKS: root::PaHostApiTypeId = 11;
    pub const PaHostApiTypeId_paJACK: root::PaHostApiTypeId = 12;
    pub const PaHostApiTypeId_paWASAPI: root::PaHostApiTypeId = 13;
    pub const PaHostApiTypeId_paAudioScienceHPI: root::PaHostApiTypeId = 14;
    #[doc = " Unchanging unique identifiers for each supported host API. This type"]
    #[doc = "is used in the PaHostApiInfo structure. The values are guaranteed to be"]
    #[doc = "unique and to never change, thus allowing code to be written that"]
    #[doc = "conditionally uses host API specific extensions."]
    #[doc = ""]
    #[doc = "New type ids will be allocated when support for a host API reaches"]
    #[doc = "\"public alpha\" status, prior to that developers should use the"]
    #[doc = "paInDevelopment type id."]
    #[doc = ""]
    #[doc = "@see PaHostApiInfo"]
    pub type PaHostApiTypeId = u32;
    extern "C" {
        #[doc = " Set the host error information returned by Pa_GetLastHostErrorInfo. This"]
        #[doc = "function and the paUnanticipatedHostError error code should be used as a"]
        #[doc = "last resort.  Implementors should use existing PA error codes where possible,"]
        #[doc = "or nominate new ones. Note that at it is always better to use"]
        #[doc = "PaUtil_SetLastHostErrorInfo() and paUnanticipatedHostError than to return an"]
        #[doc = "ambiguous or inaccurate PaError code."]
        #[doc = ""]
        #[doc = "@param hostApiType  The host API which encountered the error (ie of the caller)"]
        #[doc = ""]
        #[doc = "@param errorCode The error code returned by the native API function."]
        #[doc = ""]
        #[doc = "@param errorText A string describing the error. PaUtil_SetLastHostErrorInfo"]
        #[doc = "makes a copy of the string, so it is not necessary for the pointer to remain"]
        #[doc = "valid after the call to PaUtil_SetLastHostErrorInfo() returns."]
        pub fn PaUtil_SetLastHostErrorInfo(
            hostApiType: root::PaHostApiTypeId,
            errorCode: ::std::os::raw::c_long,
            errorText: *const ::std::os::raw::c_char,
        );
    }
    extern "C" {
        #[doc = " Allocate size bytes, guaranteed to be aligned to a FIXME byte boundary"]
        pub fn PaUtil_AllocateMemory(size: ::std::os::raw::c_long) -> *mut ::std::os::raw::c_void;
    }
    extern "C" {
        #[doc = " Realease block if non-NULL. block may be NULL"]
        pub fn PaUtil_FreeMemory(block: *mut ::std::os::raw::c_void);
    }
    extern "C" {
        #[doc = " Return the number of currently allocated blocks. This function can be"]
        #[doc = "used for detecting memory leaks."]
        #[doc = ""]
        #[doc = "@note Allocations will only be tracked if PA_TRACK_MEMORY is #defined. If"]
        #[doc = "it isn't, this function will always return 0."]
        pub fn PaUtil_CountCurrentlyAllocatedBlocks() -> ::std::os::raw::c_int;
    }
    extern "C" {
        #[doc = " Initialize the clock used by PaUtil_GetTime(). Call this before calling"]
        #[doc = "PaUtil_GetTime."]
        #[doc = ""]
        #[doc = "@see PaUtil_GetTime"]
        pub fn PaUtil_InitializeClock();
    }
    extern "C" {
        #[doc = " Return the system time in seconds. Used to implement CPU load functions"]
        #[doc = ""]
        #[doc = "@see PaUtil_InitializeClock"]
        pub fn PaUtil_GetTime() -> f64;
    }
}
